### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by stars-spark** [mzdluo123/MiraiCD#4]
> /deploy
2022-09-04 14:42:09 I/stdout: ====start run cmd====
2022-09-04 14:42:09 I/stdout: ====run finish====
2022-09-04 14:42:09 I/stdout: ====start run cmd====
2022-09-04 14:42:09 I/stdout: 已经位于 'main'
2022-09-04 14:42:09 I/stdout: 您的分支与上游分支 'origin/main' 一致。
2022-09-04 14:42:09 I/stdout: ====run finish====
2022-09-04 14:42:09 I/stdout: ====start run cmd====
2022-09-04 14:42:11 I/stdout: 已经是最新的。
2022-09-04 14:42:11 I/stdout: ====run finish====
2022-09-04 14:42:11 I/stdout: ====start run cmd====
2022-09-04 14:42:11 I/stdout: chmod: 无法访问'gradlew': 没有那个文件或目录
2022-09-04 14:42:11 I/stdout: ====run finish====
2022-09-04 14:42:11 E/MiraiCD: java.lang.IllegalStateException: cmd execute error
java.lang.IllegalStateException: cmd execute error
	at miraicd-0.1.1.mirai2.jar//win.rainchan.mirai.miraicd.DeployTask.runCMD(DeployTask.kt:35)
	at miraicd-0.1.1.mirai2.jar//win.rainchan.mirai.miraicd.DeployTask.runBuild(DeployTask.kt:58)
	at miraicd-0.1.1.mirai2.jar//win.rainchan.mirai.miraicd.DeployTask.deployBranch(DeployTask.kt:86)
	at miraicd-0.1.1.mirai2.jar//win.rainchan.mirai.miraicd.MiraiCDMain$startDeployBranch$1.invoke(MiraiCDMain.kt:106)
	at miraicd-0.1.1.mirai2.jar//win.rainchan.mirai.miraicd.MiraiCDMain$startDeployBranch$1.invoke(MiraiCDMain.kt:103)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by mzdluo123** [comment]
请确保你的项目文件夹存在gradle wrapper
https://docs.gradle.org/current/userguide/gradle_wrapper.html
